version: "3"

services:
  mysql-db:
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: dbuserpwd
      MYSQL_DATABASE: boilerplate_db
    ports:
      - "3306:3306"
    expose:
      - "3306"
    # volumes:
    #   - db_data:/var/lib/mysql
    networks:
      - boilerplate-network

  node-app:
    build:
      context: ./nodejs-api
      dockerfile: Dockerfile
    command: node server.js
    restart: on-failure
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    expose:
      - "8080"
    
    networks:
      - boilerplate-network

  web-client:
    build:
      context: ./react-crud
      dockerfile: Dockerfile
    command: serve -s build
    restart: on-failure
    
    ports:
      - "5000:5000"
    expose:
      - "5000"
    
    networks:
      - boilerplate-network



networks:
  boilerplate-network:
    driver: bridge